/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContainerBody: typeof import('./src/components/layout/ContainerBody.vue')['default']
    Demo: typeof import('./src/components/Demo.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HeaderLeft: typeof import('./src/components/layout/HeaderLeft.vue')['default']
    HeaderMidium: typeof import('./src/components/layout/HeaderMidium.vue')['default']
    HeaderRight: typeof import('./src/components/layout/HeaderRight.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutContainer: typeof import('./src/components/layout/LayoutContainer.vue')['default']
    LeftContainer: typeof import('./src/components/layout/LeftContainer.vue')['default']
    MyMenuItem: typeof import('./src/components/layout/MyMenuItem.vue')['default']
    RightContainer: typeof import('./src/components/layout/RightContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
